name: Create Environment 

on:
  push:
  pull_request:

jobs:

  pytest:

    runs-on: 'ubuntu-20.04'

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout github repo
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ hashFiles('environment.yml') }}

      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: aim_test
          environment-file: environment.yml
          auto-update-conda: true
          auto-activate-base: false

      - name: Conda list
        run: conda list


